# Generated by Django 3.2.3 on 2021-05-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='alimentos')),
                ('descripcion', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'alimento',
                'verbose_name_plural': 'alimentos',
            },
        ),
    ]
