# Generated by Django 3.2.3 on 2021-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos', '0004_remove_reservacion_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='hora',
            field=models.CharField(max_length=20),
        ),
    ]
